version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Secret!Passw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: foosball
    ports:
        - 5432:5432
    volumes: 
        - ./database.sql:/docker-entrypoint-initdb.d/database.sql
